### ISSUE TITLE
Where are sources?

### ISSUE THREAD

**Issue by exander77** [ProtonMail/inbox-desktop#15]
And why is it such a shit?

Electron app I made in a few hours is orders of magnitude better than this shit.

The app is also crashing electron all the time.

I have tray icon with count of received e-mails from last it was active etc.

Who works on it? High school student?

**Comment by flavienbonvin** [comment]
Hello, I'm the one who worked on the application. We will share the sources of the version 1.0.1 shortly, I will comment on this merge request once it's online.

I'm very sorry that you experienced crashes with the application. I would like to know a bit more about your setup and what can cause the issue. Could you share your OS and its version, please? 

Also, what creates the crash of the application? Are there specific actions you do that crash the app consistently, or is it random? 

Regarding the tray icon, this is something we want to implement, it's on our radar, but I don't have any ETA yet. I'm quite curious about your application, is it publicly available somewhere or are you willing to share it with me?

**Comment by halotroop2288** [comment]
Please do share, @exander77. It's pretty disappointing that the official app is such garbage.

- Not being available as a Flatpak, providing official downloads only for Debian-likes and Fedora-likes
- Not having the sources published
- Being incompatible with native Wayland, causing major graphical issues.
- Requiring a *paid subscription* to use it
  ![](https://github.com/ProtonMail/inbox-desktop/assets/30361266/f1116e36-682a-40c4-a0bc-6784ddb65584)

And I refuse to even test it further than that, as ProtonMail is supposed to be *free* and open-source software.

I don't know what Proton is trying to do by pushing all this new paid nonsense constantly, but I appreciated that at least the core service was free.
Now I'm looking into other providers because I can't even use their desktop client without a subscription. Maybe you can change my mind with a better app.

**Comment by flavienbonvin** [comment]
Update, the sources are available on the latest release: https://github.com/ProtonMail/inbox-desktop/releases/tag/v1.0.1 

@halotroop2288 I can shed some light on some of your comments. Thanks for the feedback.

* Not being available as a Flatpak, providing official downloads only for Debian-likes and Fedora-likes
We wanted to have this for the release, but due to an issue with Flatpak on Docker, we decided to postpone this. It's not out of the equation for now, but not on top of our backlog. Also, adding Flatpak is not as easy as clicking a button, there are many things that go into supporting a new packaging format, such as testing, pipelines to push the releases, ensuring updates, ...  

* Not having the sources published
We will publish the sources for every release from now on. We wanted to make sure that everything was alright on our side before sharing anything.

* Being incompatible with native Wayland, causing major graphical issues.
The Linux application is still in beta, we're well aware that the current experience is not perfect, but we're working to make it right. There are many different configurations, making supporting this platform harder, this is also why we decided to go with a limited amount of packaging format for the first release.
