### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [ProtonMail/inbox-desktop#6]
1. If this is an electron app, how did you fail to compile and release for linux?
2. Why electron if you can, with [tauri](https://github.com/tauri-apps/tauri), cross-compile for Win/Mac/Lin/And/Ios all from the same framework; and
  a) unify features and user experience across platforms, 
  b) reduce programmer cognitive load by sharing a codebase across 5 platforms?

**Comment by traktuner** [comment]
Was already answered here:
https://github.com/ProtonMail/inbox-desktop/issues/2#issuecomment-1882630162

**Comment by flavienbonvin** [comment]
Hi, the answer @traktuner linked explains why we went for Electron instead of Tauri. I can also add that although promising, it's challenging to find any real adoption of Tauri (by large companies). The solution is promising on paper, but it feels like people aren't using it at a large scale yet.

Regarding Linux, we plan to add support in early 2024. We decided to go for Windows and macOS first because it's the largest platform used by Proton users. Furthermore, releasing the application to a new platform doesn't come for free. We need to plan for testing, automatic deployment, application signing, ... This explain why Linux was not part of the initial release

**Comment by ParaplegicRacehorse** [comment]
> ... why we went for Electron instead of Tauri. ... adoption of Tauri (by large companies). The solution is promising on paper, but it feels like people aren't using it at a large scale yet.

I cannot find fault in the reasoning, per se, though I also cannot agree with it. I have universally had bad experience with electron applications; particularly with unnecessarily large resource-usage. That, and  remarkably few developers ever update to a new electron version with bug and security fixes; especially big-company software vendors. Grrr...

And while I cannot find fault with your statement about corporate adoption, I also can't help but wonder how much this is a chick-and-egg problem.

I also think there is a similar chicken-egg problem with WASM/WASI. The only place I've seen eager adoption of WebAssembly is in the cryptocurrency "web3" space. Yet it holds so much potential.

> Regarding Linux, we plan to add support in early 2024. We decided to go for Windows and macOS first because it's the largest platform used by Proton users. Furthermore, releasing the application to a new platform doesn't come for free. We need to plan for testing, automatic deployment, application signing, ... This explain why Linux was not part of the initial release

I feel like this is less an issue because you're using an electron container. But I don't write electron apps, so what do I know?

Thank you both for answering. I am waiting (im)patiently for a Verified flatpak to appear at Flathub.
